/*
  __  __  ____ _______ ____  _____  _      _____ _   _ ______
 |  \/  |/ __ \__   __/ __ \|  __ \| |    |_   _| \ | |  ____|
 | \  / | |  | | | | | |  | | |__) | |      | | |  \| | |__
 | |\/| | |  | | | | | |  | |  _  /| |      | | | . ` |  __|
 | |  | | |__| | | | | |__| | | \ \| |____ _| |_| |\  | |____
 |_|  |_|\____/  |_|  \____/|_|  \_\______|_____|_| \_|______|

*/

#ifndef _ERRO_LIST_H
#define _ERRP_LIST_H

#define ERROR_USER_NOT_PERMITION "ERROR USER NOT PERMITION"
#define ERROR_PASSWORD_WRONG "ERROR WRONG PASSWORD"
#define ERROR_ELEMENT "ERROR ELEMENT"
#define ERROR_USER_NOT_FOUND "ERROR USER NOT FOUND"
#define ERROR_INPUT_DATA "ERROR INPUT DATA"
#define ERROR_INPUT_COMMAND "ERROR INPUT COMMAND"
#define ERROR_CMD "ERROR COMMAND"
#define ERROR_GET "ERROR GET"
#define ERROR_PARAMETER "ERROR PARAMETER"
#define ERROR_RESET "ERROR RESET"
#define ERROR_SET "ERROR SET"
/* #define ERROR_LIMIT_USERS "ERROR LIMIT USERS" */
#define ERROR_WEEK_DAY "ERROR WEEK DAY"
#define ERROR_FB_NOT_ATIVE "ERROR FEEDBACK NOT ATIVE"
#define ERROR_USER_ALREADY_EXISTS "ERROR USER ALREADY EXISTS" 
#define ERROR_ADD_USER "ERROR ADD USER" 
#define ERROR_USER_WIEGAND_ALREADY_EXIST "$ 1"
#define ERROR_USER_RF_ALREADY_EXIST "$ 2"


#define ERROR_WRONG_LIMIT_DATE 1//"ERROR WRONG LIMIT DATE"
#define ERROR_WRONG_WEEK_DAYS 2//"ERROR WRONG WEEK DAYS"
#define ERROR_WRONG_END_TIME 3//"ERROR WRONG END TIME"
#define ERROR_WRONG_START_TIME 4//"ERROR WRONG START TIME"
#define ERROR_WRONG_START_DATE 5//"ERROR WRONG START DATE"
#define ERROR_WRONG_PHONE_NUMBER 6//"ERROR WRONG PHONE NUMBER"
#define ERROR_WRONG_RELAY_PERMITION 7//"ERROR WRONG RELAY PERMITION"
#define ERROR_WRONG_TIME_DATA 8//"ERROR WRONG TIME DATA" 
#define ERROR_NAME_LENGTH 9//"ERROR NAME LENGTH"
#define ERROR_NEW_USER_ALREADY_EXISTS 10 
#define ERROR_NEW_USER_SET 11//"ERROR NAME LENGTH"
#define ERROR_NEW_USER_INPUT_DATA 12//"ERROR NAME LENGTH"
#define ERROR_NEW_USER_ADD 13
#define ERROR_WRONG_ERASE_USER_AFTER_DATE 14//"ERROR WRONG RELAY PERMITION"
#define ERROR_LIMIT_USERS 15//"ERROR WRONG RELAY PERMITION"
#define ERROR_WIEGAND_ALREADY_EXIST 16//"ERROR WRONG RELAY PERMITION"
#define ERROR_RF_ALREADY_EXIST 17

#endif